spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboottest
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.cosine.springbootdemoorder.entity.Order
  mapper-locations: classpath:mapper/*.xml

# debug 打印sql语句
logging:
  level:
    com.cosine.springbootdemoorder.dao: debug

server:
  #端口号
  port: 9090


# nacos 相关配置
nacos:
  # 配置
  config:
    server-addr: 127.0.0.1:8848
    # 服务发现
  discovery:
    server-addr: 127.0.0.1:8848