spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboottest
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.cosine.demo.domain.Order
  mapper-locations: classpath:mapper/*.xml

# debug 打印sql语句
logging:
  level:
    com.cosine.demo.dao: debug

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  params: count=countSql
  supportMethodsArguments: true